image: docker
services:
  - docker:dind

build:
  stage: build
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /build/
      - $CI_COMMIT_TAG =~ /build/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - cd jupyterhub/jupyterlab-cpu && docker build -f foundation/Dockerfile -t $CI_REGISTRY/bayes-cluster/foundation:$IMAGE_TAG ./foundation
    - docker push $CI_REGISTRY/bayes-cluster/foundation:$IMAGE_TAG
