image: docker
services:
  - docker:dind

cpu:
  stage: build
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /build/
      - $CI_COMMIT_TAG =~ /build/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - cd jupyterhub/jupyterlab-cpu && docker build -f $PACKAGE/Dockerfile -t $CI_REGISTRY/bayes-cluster/staging-container/$PACKAGE:$IMAGE_TAG ./$PACKAGE
    - docker push $CI_REGISTRY/bayes-cluster/staging-container/foundation:$IMAGE_TAG
  parallel:
    matrix:
      - PACKAGE: [foundation, base-notebook, mini-notebook, scipy-notebook, datascience-notebook]
    
