image: docker
services:
  - docker:dind

build:
  stage: build
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /build/
      - $CI_COMMIT_TAG =~ /build/
  before_script:
    - docker login $CI_REGISTRY -u GITLAB_REGISTRY_USER -p GITLAB_REGISTRY_PASSWORD
  script:
    - cd jupyterhub/jupyterlab-cpu && docker build -f foundation/Dockerfile -t bayes-cluster/foundation:$CI_COMMIT_TAG ./foundation && docker push
